server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8761/eureka/, http://xiaoqiang:xiaoqiang@localhost:8762/eureka/, http://xiaoqiang:xiaoqiang@localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

zuul:
  routes:
    # 调用/invoker/invoker时， 会将请求重定向到feign-invoker服务上面的/invoker, 下面两种写法等效
    # stripPrefix: true 默认会去掉前缀
    # feign-invoker: /invoker/**
    feign-invoker:
      path: /feign/**
      serviceId: feign-invoker
    ribbon-invoker:
      path: /ribbon/**
      serviceId: ribbon-invoker
  host:
    connect-timeout-millis: 10000
    connection-request-timeout-millis: 10000
  # 关闭不需要执行的过滤器, 执行需要关闭的类名，过滤器的类型
  SecondPreFilter:
    pre:
      disable: true
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: ["*"]