server:
  port: 8761

spring:
  application:
    name: registry-center
  profiles: 8761
  security:
    user:
      name: xiaoqiang
      password: xiaoqiang

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8762/eureka/, http://xiaoqiang:xiaoqiang@localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true

---
server:
  port: 8762

spring:
  application:
    name: registry-center
  profiles: 8762
  security:
    user:
      name: xiaoqiang
      password: xiaoqiang

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8761/eureka/, http://xiaoqiang:xiaoqiang@localhost:8763/eureka/
    # 是否将自己注册到注册中心，集群部署时需要设置成true
    register-with-eureka: true
    # 是否从远程同步信息
    fetch-registry: true

---
server:
  port: 8763

spring:
  application:
    name: registry-center
  profiles: 8763
  security:
    user:
      name: xiaoqiang
      password: xiaoqiang

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8762/eureka/, http://xiaoqiang:xiaoqiang@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true