server:
  port: 7700

spring:
  application:
    name: sleuth-server

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8761/eureka/, http://xiaoqiang:xiaoqiang@localhost:8762/eureka/, http://xiaoqiang:xiaoqiang@localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 关闭自动检测请求，否则启动报错IllegalArgumentException
management:
  metrics:
    web:
      server.auto-time-requests: false