server:
  port: 8081

spring:
  application:
    name: server-provider
  profiles: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

---
server:
  port: 8082

spring:
  application:
    name: server-provider
  profiles: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

---
server:
  port: 8083

spring:
  application:
    name: server-provider
  profiles: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}