server:
  port: 9200

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoqiangjava/config-demo.git
          username: xxxxx
          password: xxxxx
          search-paths: config-file

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@localhost:8761/eureka/, http://xiaoqiang:xiaoqiang@localhost:8762/eureka/, http://xiaoqiang:xiaoqiang@localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}