server:
  port: 9092

spring:
  application:
    name: feign-invoker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}